import { BaseRule } from "./BaseRule.js";
import { Docs } from "./docs.js";
import type { Finding, RuleOptions, ServerSnapshot } from "../types.js";

type CrudClass = "read" | "create" | "update" | "delete";

export class DesignCrudMirror extends BaseRule {
  readonly id = "design/crud-mirror";
  readonly category = "design" as const;
  readonly severity = "warn" as const;
  readonly weight = 4;
  readonly docsUrl = Docs.rule("design/crud-mirror");
  readonly rationale =
    "A get/create/update/delete family over one noun is the fingerprint of an " +
    "OpenAPI-autogenerated surface: it mirrors your REST API, not your users' " +
    "intents. Agents work in workflows, not endpoints — consolidate around tasks.";

  private static readonly VERB_CLASSES: ReadonlyMap<string, CrudClass> = new Map([
    ["get", "read"], ["list", "read"], ["fetch", "read"], ["read", "read"],
    ["create", "create"], ["add", "create"], ["new", "create"],
    ["update", "update"], ["set", "update"], ["change", "update"],
    ["rename", "update"], ["edit", "update"], ["modify", "update"],
    ["delete", "delete"], ["remove", "delete"]
  ]);

  private static noun(tokens: string[]): string {
    return tokens
      .slice(1)
      .map((t) => t.replace(/s$/, ""))
      .join("_");
  }

  check(snapshot: ServerSnapshot, _options: RuleOptions = {}): Finding[] {
    const families = new Map<string, Map<CrudClass, string[]>>();
    for (const tool of snapshot.tools) {
      const tokens = BaseRule.nameTokens(tool.name);
      const crudClass = tokens[0] ? DesignCrudMirror.VERB_CLASSES.get(tokens[0]) : undefined;
      if (!crudClass || tokens.length < 2) continue;
      const noun = DesignCrudMirror.noun(tokens);
      const family = families.get(noun) ?? new Map<CrudClass, string[]>();
      family.set(crudClass, [...(family.get(crudClass) ?? []), tool.name]);
      families.set(noun, family);
    }
    const findings: Finding[] = [];
    for (const [noun, family] of families) {
      if (family.size < 3) continue;
      const members = [...family.values()].flat();
      findings.push(
        this.finding({
          message: `CRUD mirror over "${noun}": ${members.length} tools spanning ${family.size} verb classes — one-tool-per-endpoint shape. Consider a workflow-shaped consolidation.`,
          evidence: members.join(", ")
        })
      );
    }
    return findings;
  }
}
